apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: WEBHOOK_HOST
    http:
      paths:
      - path: /sonarqube(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sonarqube-sonarqube
            port:
              number: 9000
