---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - supplychain.blanketops.dev
  resources:
  - repositorysources
  - supplychains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supplychain.blanketops.dev
  resources:
  - repositorysources/finalizers
  - supplychains/finalizers
  verbs:
  - update
- apiGroups:
  - supplychain.blanketops.dev
  resources:
  - repositorysources/status
  - supplychains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
