apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups: ["supplychain.blanketops.dev"]
  resources: ["supplychains","supplychains/status","supplychains/finalizers","imagebuilds","imagebuilds/status","imagebuilds/finalizers","imagebuildresults","imagebuildresults/status","imagebuildresults/finalizers","imagesignatures","imagesignatures/status","imagesignatures/finalizers","githubwebhooks","githubwebhooks/status","githubwebhooks/finalizers"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["tekton.dev"]
  resources: ["tasks","pipelineruns","pipelines","taskruns"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners","triggerbindings","triggertemplates"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["serviceaccounts","serviceaccounts/token","secrets","events","configmaps"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
