---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.sigstore.dev
  resources:
  - clusterimagepolicies
  - trustroots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spire.spiffe.io
  resources:
  - clusterstaticentries
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - supplychain.blanketops.dev
  resources:
  - githubwebhooks
  - imagebuildresults
  - imagebuilds
  - imagesignatures
  - supplychainpolicies
  - supplychains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supplychain.blanketops.dev
  resources:
  - githubwebhooks/finalizers
  - imagebuildresults/finalizers
  - imagebuilds/finalizers
  - imagesignatures/finalizers
  - supplychainpolicies/finalizers
  - supplychains/finalizers
  verbs:
  - update
- apiGroups:
  - supplychain.blanketops.dev
  resources:
  - githubwebhooks/status
  - imagebuildresults/status
  - imagebuilds/status
  - imagesignatures/status
  - supplychainpolicies/status
  - supplychains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - customruns
  - pipelineruns
  - pipelines
  - taskruns
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - customruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
