## Append samples of your project ##
resources:
- supplychain_v1alpha1_secretsstore.yaml
- supplychain_v1alpha1_supplychain.yaml
#- supplychain_v1alpha1_imagebuild.yaml
- supplychain_v1alpha1_signingrole.yaml
- supplychain_v1alpha1_eventlistenerrole.yaml

#- supplychain_v1alpha1_imagesignature.yaml
#- supplychain_v1alpha1_imagebuildresult.yaml
- supplychain_v1alpha1_githubwebhook.yaml
- supplychain_v1alpha1_supplychainpolicy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
