apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secure-software-supply-chain-supply-chain-store
spec:
  provider:
    fake:
      data:
      # ----------------------------
      # Git SSH (Build source clone)
      # ----------------------------
      - key: "/supplychain/git/ssh-privatekey"
        value: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACCD72OKXV78Qqiq4N5J+WelyW+nQ8VInJHKZzMHVLW8hQAAAJjt4lPL7eJT
          ywAAAAtzc2gtZWQyNTUxOQAAACCD72OKXV78Qqiq4N5J+WelyW+nQ8VInJHKZzMHVLW8hQ
          AAAEC3+TlS+NONMChi19OT8YboUqLqV+7m4Q23Xr+yoksbO4PvY4pdXvxCqKrg3kn5Z6XJ
          b6dDxUickcpnMwdUtbyFAAAAFW50bGFsZXRzaTg2QGdtYWlsLmNvbQ==
          -----END OPENSSH PRIVATE KEY-----

      - key: "/supplychain/git/ssh-publickey"
        value: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIPvY4pdXvxCqKrg3kn5Z6XJb6dDxUickcpnMwdUtbyF ntlaletsi86@gmail.com

      - key: "/supplychain/git/known-hosts"
        value: |
          # github.com:22 SSH-2.0-9ee1b2f
          github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          # github.com:22 SSH-2.0-9ee1b2f
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
          # github.com:22 SSH-2.0-9ee1b2f
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          # github.com:22 SSH-2.0-9ee1b2f
          # github.com:22 SSH-2.0-9ee1b2f
      - key: "/supplychain/git/ssh-config"
        value: |
          Host github.com
            HostName github.com
            User git
            IdentityFile /home/git/.ssh/id_rsa
            IdentitiesOnly yes
            StrictHostKeyChecking yes
        # Registry auth (Shipwright / Kaniko)
        # ----------------------------
      - key: "/supplychain/registry/config"
        value: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "bmthbnllemlzb2x1dGlvbnM6ZGNrcl9wYXRfdG1ETWd1aC1FckRFRjBwSG5oUk54UHJFU09Z"
              }
            }
          }
      - key: /supplychain/sonarqube/token
        value: squ_828b9ce6fe2a8f9936216f77d3d61b4641f28cd5

      - key: /supplychain/github/pat
        value: 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
