apiVersion: supplychain.blanketops.dev/v1alpha1
kind: SupplyChain
metadata:
  labels:
    app.kubernetes.io/name: secure-software-supply-chain
    app.kubernetes.io/managed-by: kustomize
  name: for-kaniko-app
spec:
  repository: ntlaletsi70/for-kaniko-app
  webhookHost: pop-os.tailf8145.ts.net
  image:
    registry: docker.io
    name: nkanyezisolutions/for-kaniko-app
    tagStrategy: git-sha
    cloneSecret: github-ssh-credentials
    registrySecret: registry-credentials
  steps:
    buildpacks: true
    #trivy: false
    sign: true
    attest: true
    sonarQube:
      #serverURL: http://sonarqube-sonarqube.secure-software-supply-chain-supply-chain.svc.cluster.local:9000 #deployed
      serverURL: http://sonarqube-sonarqube.default.svc.cluster.local:9000/sonarqube
      tokenSecretRef: sonarqube-token
      projectKey: ntlaletsi70_for-kaniko-app

  signing:
    fulcioURL: http://fulcio-server.fulcio-system.svc.cluster.local
    rekorURL: http://rekor-server.rekor-system.svc.cluster.local
    ctLogURL: http://ctlog.ctlog-system.svc/fulcio
  serviceAccountName: supply-chain-runner
