apiVersion: supplychain.blanketops.dev/v1alpha1
kind: RepositorySource
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments-supply-chain
    app.kubernetes.io/managed-by: kustomize
  name: for-kaniko-app
spec:
  provider: github # extensible — gitlab, bitbucket later
  repository: ntlaletsi70/for-kaniko-app
  branch: master
  tokenSecretRef: github-pat # PAT for API access
  listenerURL: https://abc123.ngrok.io # injected as repo secret
  webhook:
    inject: true # controller creates the workflow file
    hmacSecretRef: webhook-hmac
  oidc:
    audience: sigstore # minted in the injected action
    forwardTo: chains # Chains picks it up
