apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: aws-secrets-manager-secret-store-secure-supply-chain
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-manager-auth-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secrets-manager-auth-secret
            key: secret-access-key
