apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafeas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafeas
  template:
    metadata:
      labels:
        app: grafeas
    spec:
      containers:
      - name: grafeas
        image: emunari/grafeas-server
        args:
        - --grpc-port=8080
        - --http-port=8081
        ports:
        - containerPort: 8080
        - containerPort: 8081
